// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnachtwjumapjmabrrrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuYWNodHdqdW1hcGptYWJycnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTM5NDksImV4cCI6MjA2OTg4OTk0OX0.NsUlD_M7y3XAjXQkIXNllK3H87oTUL5_hGh151WYEzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});